twig:
    default_path: '%kernel.project_dir%/templates'

when@test:
    twig:
        strict_variables: true
    services:
    App\Twig\TranslationExtension:
        parent: jms_translation.twig.extension
        tags:
            - { name: twig.extension }
